ALTER TABLE documents ADD COLUMN IF NOT EXISTS mime_type VARCHAR(150) NOT NULL DEFAULT 'application/octet-stream';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS ocr_provider VARCHAR(100) NULL;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS ocr_text LONGTEXT NULL;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS ocr_error LONGTEXT NULL;
