"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ArrowUpRight, FilePdf, MagnifyingGlass, Printer } from "@phosphor-icons/react";
import { AppShell, StatusBadge } from "@/components/app-shell";
import { ApiDocument, WorkloadReportRow, formatThaiDate, getWorkloadReport, searchDocuments, statusLabel } from "@/lib/api";

type SearchFilters = { query: string; position: string; orderType: string; dateFrom: string; dateTo: string };

export default function SearchPage() {
  const [filters, setFilters] = useState<SearchFilters>({ query: "", position: "", orderType: "", dateFrom: "", dateTo: "" });
  const [submitted, setSubmitted] = useState<SearchFilters>({ query: "", position: "", orderType: "", dateFrom: "", dateTo: "" });
  const [results, setResults] = useState<ApiDocument[]>([]);
  const [workload, setWorkload] = useState<WorkloadReportRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    Promise.all([searchDocuments(submitted), getWorkloadReport(submitted)]).then(([documentsResponse, workloadResponse]) => { setResults(documentsResponse.data); setWorkload(workloadResponse.data); setError(""); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false));
  }, [submitted]);

  const submit = (event: FormEvent) => { event.preventDefault(); setLoading(true); setSubmitted({ ...filters, query: filters.query.trim(), position: filters.position.trim() }); };
  const updateFilter = (key: keyof SearchFilters, value: string) => setFilters((current) => ({ ...current, [key]: value }));

  return <AppShell breadcrumb="หน้าหลัก / การค้นหาและรายงาน" title="ค้นหาข้อมูลการแต่งตั้ง" description="ค้นหาจากข้อมูลที่เจ้าหน้าที่ตรวจสอบแล้วและข้อมูลรอการยืนยัน โดยเชื่อมต่อฐานข้อมูล MySQL จริง"><div className="space-y-6">
    <section className="card p-5"><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="relative sm:col-span-2 lg:col-span-3"><MagnifyingGlass size={19} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#8a9aaa]" /><input value={filters.query} onChange={(event) => updateFilter("query", event.target.value)} placeholder="ชื่อบุคคล เลขที่คำสั่ง คณะกรรมการ หรือคำค้น OCR" className="focus-ring h-12 w-full rounded-full border-0 bg-[var(--pill)] pl-11 pr-4 text-sm text-[var(--navy)] outline-none placeholder:text-[var(--subtle)]" /></div><button type="submit" className="focus-ring h-12 rounded-lg bg-[var(--accent)] px-6 text-sm font-semibold text-white hover:bg-[var(--accent-strong)]">ค้นหาข้อมูล</button><input value={filters.position} onChange={(event) => updateFilter("position", event.target.value)} placeholder="ตำแหน่ง / บทบาท" className="focus-ring h-10 rounded-lg border border-[var(--line)] px-3 text-sm outline-none focus:border-[var(--accent)]" /><select value={filters.orderType} onChange={(event) => updateFilter("orderType", event.target.value)} className="focus-ring h-10 rounded-lg border border-[var(--line)] bg-white px-3 text-sm outline-none focus:border-[var(--accent)]"><option value="">ทุกประเภทคำสั่ง</option><option value="แต่งตั้ง">แต่งตั้ง</option><option value="มอบหมาย">มอบหมาย</option><option value="ยกเลิก">ยกเลิก</option></select><label className="flex items-center gap-2 text-xs text-[var(--muted)]"><span>ตั้งแต่</span><input type="date" value={filters.dateFrom} onChange={(event) => updateFilter("dateFrom", event.target.value)} className="focus-ring h-10 min-w-0 flex-1 rounded-lg border border-[var(--line)] px-2 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="flex items-center gap-2 text-xs text-[var(--muted)]"><span>ถึง</span><input type="date" value={filters.dateTo} onChange={(event) => updateFilter("dateTo", event.target.value)} className="focus-ring h-10 min-w-0 flex-1 rounded-lg border border-[var(--line)] px-2 text-sm outline-none focus:border-[var(--accent)]" /></label></form><p className="mt-3 text-xs text-[var(--muted)]">ค้นหาจาก documents, ชื่อ/ตำแหน่งใน appointments, ข้อความ OCR และช่วงวันที่ออกคำสั่ง</p></section>
    {error && <div className="rounded-lg bg-[var(--danger-soft)] p-4 text-sm font-medium text-[var(--danger)]">{error}</div>}
    <section className="overflow-hidden card"><div className="border-b border-[var(--line)] p-5"><h2 className="text-base font-semibold text-[var(--navy)] lg:text-lg">รายงานภาระงานคณะกรรมการ</h2><p className="mt-1 text-sm text-[var(--muted)]">นับจากเอกสารที่เจ้าหน้าที่ตรวจสอบและยืนยันแล้ว สามารถพิมพ์หรือบันทึกเป็น PDF ได้</p></div><div className="overflow-x-auto"><table className="data-grid w-full min-w-[760px] text-left text-sm"><thead><tr><th className="px-5 py-3">ชื่อบุคคล</th><th className="px-4 py-3">ตำแหน่ง</th><th className="px-4 py-3">จำนวนคำสั่ง</th><th className="px-4 py-3">รายการแต่งตั้ง</th><th className="px-5 py-3">ยืนยันแล้ว</th></tr></thead><tbody>{workload.map((row) => <tr key={`${row.fullName}-${row.position}`}><td className="px-5 py-3 font-semibold text-[var(--ink)]">{row.fullName}</td><td className="px-4 py-3 text-[var(--muted)]">{row.position || "-"}</td><td className="px-4 py-3 text-[var(--ink)]">{row.documentCount.toLocaleString("th-TH")}</td><td className="px-4 py-3 text-[var(--ink)]">{row.appointmentCount.toLocaleString("th-TH")}</td><td className="px-5 py-3 text-[var(--success)]">{row.verifiedCount.toLocaleString("th-TH")}</td></tr>)}{workload.length === 0 && <tr><td colSpan={5} className="px-5 py-8 text-center text-sm text-[var(--muted)]">ยังไม่มีข้อมูลภาระงานจากเอกสารที่ยืนยันแล้ว</td></tr>}</tbody></table></div></section>
    <section className="overflow-hidden card"><div className="flex items-center justify-between border-b border-[var(--line)] p-5"><div><h2 className="text-base font-semibold text-[var(--navy)] lg:text-lg">รายการเอกสารที่พบ</h2><p className="mt-1 text-sm text-[var(--muted)]">{loading ? "กำลังค้นหา..." : `พบ ${results.length.toLocaleString("th-TH")} รายการ`}</p></div><button type="button" onClick={() => window.print()} className="focus-ring inline-flex items-center gap-2 rounded-lg border border-[var(--line)] px-3 py-2 text-xs font-semibold text-[var(--muted)] hover:border-[var(--accent)] hover:text-[var(--accent)]"><Printer size={16} /> พิมพ์ / บันทึก PDF</button></div><div className="overflow-x-auto"><table className="data-grid w-full min-w-[900px] text-left text-sm"><thead><tr><th className="px-5 py-3">เอกสาร</th><th className="px-4 py-3">เลขที่คำสั่ง</th><th className="px-4 py-3">คณะกรรมการ</th><th className="px-4 py-3">วันที่มีผล</th><th className="px-4 py-3">สถานะ</th><th className="px-5 py-3" /></tr></thead><tbody>{results.map((document) => <tr key={document.id} className="group transition hover:bg-[var(--brand-blue-pale)]"><td className="px-5 py-4"><Link href={`/documents/${document.id}`} className="focus-ring flex items-center gap-3 rounded-md"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><FilePdf size={19} weight="duotone" /></span><span className="min-w-0"><span className="block max-w-[280px] truncate font-semibold text-[var(--ink)]">{document.title || document.originalFilename}</span><span className="mt-1 block text-xs text-[var(--muted)]">{document.originalFilename}</span></span></Link></td><td className="px-4 py-4 font-semibold text-[var(--ink)]">{document.orderNo || "ยังไม่พบ"}</td><td className="px-4 py-4 text-[var(--muted)]">{document.committee || "ยังไม่พบ"}</td><td className="px-4 py-4 text-[var(--muted)]">{formatThaiDate(document.effectiveDate)}</td><td className="px-4 py-4"><StatusBadge status={statusLabel(document.status)} /></td><td className="px-5 py-4 text-right"><Link href={`/documents/${document.id}`} className="focus-ring inline-flex rounded-md p-1.5 text-[var(--muted)] opacity-0 transition group-hover:opacity-100 hover:bg-[#eef4f6] hover:text-[var(--accent)]"><ArrowUpRight size={17} /></Link></td></tr>)}{!loading && results.length === 0 && <tr><td colSpan={6} className="px-5 py-16 text-center"><MagnifyingGlass size={28} className="mx-auto text-[#a9b6c2]" /><p className="mt-3 text-sm font-semibold text-[var(--ink)]">ไม่พบข้อมูล</p><p className="mt-1 text-xs text-[var(--muted)]">ลองค้นหาด้วยชื่อบุคคล เลขที่คำสั่ง หรือคำจากเอกสาร</p></td></tr>}</tbody></table></div></section>
  </div></AppShell>;
}
