"use client";

import { useEffect, useState } from "react";
import { ClockCounterClockwise, GearSix, ShieldCheck, UserCircle, UsersThree } from "@phosphor-icons/react";
import { AppShell } from "@/components/app-shell";
import { useToast } from "@/components/toast";
import { DirectoryUser, formatThaiDate, getDirectoryUsers, getSyncRuns, SyncRun, syncDirectoryUsers } from "@/lib/api";

export default function SettingsPage() {
  const [users, setUsers] = useState<DirectoryUser[]>([]);
  const [runs, setRuns] = useState<SyncRun[]>([]);
  const [query, setQuery] = useState("");
  const [syncing, setSyncing] = useState(false);
  const toast = useToast();
  const [error, setError] = useState("");

  const load = () => Promise.all([getDirectoryUsers(query), getSyncRuns()]).then(([userResponse, runResponse]) => { setUsers(userResponse.data); setRuns(runResponse.data); setError(""); }).catch((reason: Error) => setError(reason.message));
  useEffect(() => { Promise.all([getDirectoryUsers(), getSyncRuns()]).then(([userResponse, runResponse]) => { setUsers(userResponse.data); setRuns(runResponse.data); }).catch((reason: Error) => setError(reason.message)); }, []);

  const sync = async () => { setSyncing(true); setError(""); try { const response = await syncDirectoryUsers(); toast(`sync สำเร็จ ${response.data.fetched} รายการ · เพิ่ม ${response.data.created} · แก้ไข ${response.data.updated} · ไม่เปลี่ยนแปลง ${response.data.unchanged}`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "sync ไม่สำเร็จ"); } finally { setSyncing(false); } };
  const activeUsers = users.filter((user) => user.isActive === "A").length;
  const roles = new Set(users.map((user) => user.role).filter(Boolean)).size;

  return <AppShell breadcrumb="หน้าหลัก / การบริหารระบบ" title="ผู้ใช้งานและสิทธิ์" description="รายชื่อในหน้านี้มาจากฐานข้อมูลบุคลากรที่ sync จาก External API และระบบจะเก็บประวัติการ sync ทุกครั้ง" actions={<button type="button" disabled={syncing} onClick={sync} className="focus-ring inline-flex h-12 items-center justify-center gap-2 rounded-md bg-white px-6 text-[15px] font-medium text-[var(--accent)] hover:bg-[var(--accent-soft)] disabled:opacity-50"><UsersThree size={18} />{syncing ? "กำลัง sync..." : "sync บุคลากรตอนนี้"}</button>}><div className="space-y-6">
    {error && <div className="rounded-lg bg-[var(--danger-soft)] p-4 text-sm font-medium text-[var(--danger)]">{error}</div>}
    <section className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><UserCircle size={22} weight="duotone" className="text-[var(--accent)]" /><p className="mt-4 text-xs font-semibold text-[var(--muted)]">บุคลากรในฐานข้อมูล</p><p className="mt-1 text-2xl font-bold text-[var(--ink)]">{users.length.toLocaleString("th-TH")}</p></div><div className="card p-5"><ShieldCheck size={22} weight="duotone" className="text-[var(--success)]" /><p className="mt-4 text-xs font-semibold text-[var(--muted)]">กำลังใช้งาน</p><p className="mt-1 text-2xl font-bold text-[var(--ink)]">{activeUsers.toLocaleString("th-TH")}</p></div><div className="card p-5"><ClockCounterClockwise size={22} weight="duotone" className="text-[var(--warning)]" /><p className="mt-4 text-xs font-semibold text-[var(--muted)]">รอบ sync ล่าสุด</p><p className="mt-1 text-2xl font-bold text-[var(--ink)]">{runs.length ? formatThaiDate(runs[0].startedAt) : "ยังไม่มี"}</p><p className="mt-1 text-xs text-[var(--muted)]">{roles} บทบาทจากข้อมูลจริง</p></div></section>
    <section className="overflow-hidden card"><div className="flex flex-col gap-4 border-b border-[var(--line)] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-semibold text-[var(--navy)] lg:text-lg">ฐานข้อมูลบุคลากร</h2><p className="mt-1 text-sm text-[var(--muted)]">ใช้จับคู่ชื่อจาก OCR กับข้อมูลบุคลากรในวิทยาลัย</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") load(); }} placeholder="ค้นหาชื่อ อีเมล หน่วยงาน..." className="focus-ring h-10 rounded-lg border border-[var(--line)] px-3 text-sm outline-none focus:border-[var(--accent)]" /></div><div className="overflow-x-auto"><table className="data-grid w-full min-w-[850px] text-left text-sm"><thead><tr><th className="px-5 py-3">ผู้ใช้งาน</th><th className="px-4 py-3">ตำแหน่ง</th><th className="px-4 py-3">หน่วยงาน</th><th className="px-4 py-3">บทบาท</th><th className="px-5 py-3">พบล่าสุด</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="transition hover:bg-[var(--brand-blue-pale)]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[var(--accent-soft)] text-xs font-bold text-[var(--accent)]">{(user.fullName || user.username || "?").slice(0, 2)}</span><div><p className="font-semibold text-[var(--ink)]">{user.fullName || user.username || "ไม่ระบุชื่อ"}</p><p className="mt-1 text-xs text-[var(--muted)]">{user.email || user.externalId}</p></div></div></td><td className="px-4 py-4 text-[var(--ink)]">{user.jobTitle || "-"}</td><td className="px-4 py-4 text-[var(--muted)]">{user.department || user.faculty || "-"}</td><td className="px-4 py-4 text-[var(--muted)]">{user.role || "-"}</td><td className="px-5 py-4 text-xs text-[var(--muted)]">{formatThaiDate(user.lastSeenAt)}</td></tr>)}{users.length === 0 && <tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-[var(--muted)]">ยังไม่มีข้อมูลบุคลากร กด sync หลังตั้งค่า API_KEY</td></tr>}</tbody></table></div></section>
    <section className="card p-5"><div className="flex items-center gap-3"><span className="rounded-lg bg-[var(--accent-soft)] p-2 text-[var(--accent)]"><GearSix size={20} weight="duotone" /></span><div><h2 className="text-base font-semibold text-[var(--navy)] lg:text-lg">นโยบายและงานตามเวลา</h2><p className="mt-1 text-sm text-[var(--muted)]">ระบบตั้ง cron sync รายชื่อทุกวันเวลา 05:00 น. ตาม Asia/Bangkok และเก็บ audit/sync run ไว้ตรวจสอบย้อนหลัง</p></div></div></section>
  </div></AppShell>;
}
